-- ======================================
-- Dimension Exploration
-- ======================================

--Explore All Objects in the Database 
SELECT *FROM INFORMATION_SCHEMA.TABLES

-- Explore All Columns in the Database
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- Explore All Countries our customers come from
SELECT DISTINCT 
	country
FROM gold.dim_customers

-- Explore All categories
SELECT DISTINCT
	  category
	, subcategory
	, product_name
FROM gold.dim_products
ORDER BY 1,2,3

-- Explore the date boundaries
SELECT MAX(date_of_birth) AS max_dob
	, MIN(date_of_birth) AS min_dob
	, DATEDIFF(year,MIN(date_of_birth),GETDATE()) AS oldest_customer
	, DATEDIFF(year,MAX(date_of_birth),GETDATE()) AS youngest_customer
	, MAX(create_date) AS max_create_date
	, MIN(create_date) AS min_create_date
FROM gold.dim_customers

SELECT MAX(start_date) AS max_create_date
	, MIN(start_date) AS min_create_date
FROM gold.dim_products

SELECT  MAX(order_date) AS max_order_date
	, MIN(order_date) AS min_order_date
	, MAX(shipping_date) AS max_shipping_date
	, MIN(shipping_date) AS min_shipping_date
	, MAX(due_date) AS max_due_date
	, MIN(due_date) AS min_due_date
	, DATEDIFF(month,MIN(order_date),MAX(order_date)) AS order_range_months
FROM gold.fact_sales

-- ======================================
-- Measure Exploration
-- ======================================

-- Find the Total Sales

SELECT SUM(sales_amount) AS total_sales
FROM gold.fact_sales

-- Find how many items are sold

SELECT SUM(quantity) AS total_quantity
FROM gold.fact_sales

-- Find the average selling price

SELECT AVG(price) AS average_price
FROM gold.fact_sales

-- Find the total number of orders

SELECT COUNT(DISTINCT order_number) AS number_of_orders
FROM gold.fact_sales

-- Find the total number of products

SELECT MAX(product_key) AS total_products
FROM gold.dim_products
SELECT COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products

-- Find the total number of customers

SELECT MAX(customer_key) AS total_customers
FROM gold.dim_customers
SELECT COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers

-- Find the total number of customers that has placed an order

SELECT COUNT(DISTINCT customer_key) AS total_customers_who_placed_orders
FROM gold.fact_sales


-- ============================================================
-- GENERATE a REPORT that shows all key metrics of the business
-- ============================================================

SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_name, SUM(quantity)  AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Price' AS measure_name, AVG(price)  AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Num. Orders' AS measure_name, COUNT(DISTINCT order_number)  AS measure_value FROM gold.fact_sales
UNION ALL	   
SELECT 'Total Num. Products' AS measure_name, COUNT(DISTINCT product_key)  AS measure_value FROM gold.dim_products
UNION ALL	  
SELECT 'Total Num. Customers' AS measure_name, COUNT(DISTINCT customer_key)  AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Customers Who Placed Orders' AS measure_name, COUNT(DISTINCT customer_key)  AS measure_value FROM gold.fact_sales

-- ===============================
-- Breaking Measures by Dimensions
-- ===============================

-- Find total customers by countries

SELECT 
	  country
	, COUNT(customer_key) AS total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- Find total customers by gender

SELECT 
	  gender
	, COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

-- Find total products by category

SELECT 
	  category
	, COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC
 
-- What is the average costs in each category?

SELECT 
	  category
	, AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC

-- What is the total revenue generated for each category?

SELECT 
	  category
	, SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
	ON dp.product_key = fs.product_key
GROUP BY category
ORDER BY total_revenue DESC

-- What is the total revenue generated by each customer

SELECT 
	  dc.customer_number
	, SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
	ON dc.customer_key = fs.customer_key
GROUP BY dc.customer_number
ORDER BY total_revenue DESC

-- What is the distribution of sold items across countries?

SELECT 
	  dc.country
	, SUM(quantity) AS total_products_sold
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
	ON fs.customer_key = dc.customer_key
GROUP BY dc.country
ORDER BY total_products_sold DESC

-- What is the distribution of items across gender and category?

SELECT 
	  dc.gender
	, dp.category
	, SUM(quantity) AS total_products_sold
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
	ON fs.customer_key = dc.customer_key
LEFT JOIN gold.dim_products dp
	ON fs.product_key = dp.product_key
GROUP BY dc.gender, dp.category
ORDER BY total_products_sold DESC


-- ==================================================
-- Ranking Analysis - Ordering Dimensions by Measures
-- ==================================================

-- Which 5 products generate the highest revenue?

SELECT TOP 5
	  dp.product_name
	, SUM(fs.sales_amount) AS product_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
	ON fs.product_key = dp.product_key
GROUP BY product_name
ORDER BY product_revenue DESC

SELECT TOP 5
	  dp.subcategory
	, SUM(fs.sales_amount) AS product_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
	ON fs.product_key = dp.product_key
GROUP BY subcategory
ORDER BY product_revenue DESC

-- What are the 5 worst-performing products in terms of sales?

SELECT TOP 5
	  dp.product_name
	, SUM(fs.sales_amount) AS product_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
	ON fs.product_key = dp.product_key
GROUP BY product_name
ORDER BY product_revenue 

SELECT TOP 5
	  dp.subcategory
	, SUM(fs.sales_amount) AS product_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_products dp
	ON fs.product_key = dp.product_key
GROUP BY subcategory
ORDER BY product_revenue 

-- Find the top 10 customers who have generated the highest revenue

SELECT TOP 10
	  dc.customer_id
	, dc.first_name
	, dc.last_name
	, SUM(fs.sales_amount) AS customer_revenue 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
	ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_id
	, dc.first_name
	, dc.last_name
ORDER BY customer_revenue DESC

-- The 3 customers with the fewest orders placed

SELECT TOP 3
	  dc.customer_id
	, dc.first_name
	, dc.last_name
	, COUNT(DISTINCT fs.order_number) AS customer_orders 
FROM gold.fact_sales fs
LEFT JOIN gold.dim_customers dc
	ON fs.customer_key = dc.customer_key
GROUP BY dc.customer_id
	, dc.first_name
	, dc.last_name
ORDER BY customer_orders 